name: DiscordChatBridge
authors:
  - JohnyMuffin
  - Owen2k6
version: 2.0.9
main: org.retrohaven.beta.discordchatbridge.DiscordChatBridge
depend:
  - DiscordCore
softdepend:
  - DiscordAuthentication
  - BetaDeaths